export function getCurrencyName(label) {
    return currencyNames[label];
}

const currencyNames = {
    AUD: 'Australian Dollar',
    BGN: 'Bulgarian Lev',
    BRL: 'Brazilian Real',
    CAD: 'Canadian Dollar',
    CHF: 'Swiss Franc',
    CNY: 'Chinese Yuan Renminbi',
    CZK: 'Czech Koruna',
    CYP: 'Cypriot Pound',
    DKK: 'Danish Krone',
    EEK: 'Estonian Kroon',
    EUR: 'EU Euro',
    GBP: 'Great British Pound Sterling',
    HKD: 'Hong Kong Dollar',
    HRK: 'Croatian Kuna',
    HUF: 'Hungarian Forint',
    IDR: 'Indonesian Rupiah',
    ILS: 'Israeli Shekel',
    INR: 'Indian Rupee',
    ISK: 'Icelandic Krona',
    JPY: 'Japanese Yen',
    KRW: 'South Korean Won',
    LTL: 'Lithuanian Litas',
    LVL: 'Latvian Lats',
    MTL: 'Maltese Lira',
    MXN: 'Mexican Peso',
    MYR: 'Malaysian Ringgit',
    NOK: 'Norwegian Krone',
    NZD: 'New Zealand Dollar',
    PHP: 'Philippine Peso',
    PLN: 'Polish Zloty',
    ROL: 'Romanian Leu',
    RON: 'Romanian Leu',
    RUB: 'Russian Rouble',
    SEK: 'Swedish Krona',
    SGD: 'Singapore Dollar',
    SIT: 'Slovenian Tolar',
    SKK: 'Slovak Koruna',
    THB: 'Thai  Baht',
    TRL: 'Turkish Lira',
    TRY: 'Turkish Lira',
    USD: 'US Dollar',
    ZAR: 'South African Rand'
}